// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDViTI5kA3VMKW71FhRR7l2mXIbcLjv1sE',
    appId: '1:748005715080:web:a4cfa8868f4af18b6a833d',
    messagingSenderId: '748005715080',
    projectId: 'chatapp-7b6ad',
    authDomain: 'chatapp-7b6ad.firebaseapp.com',
    storageBucket: 'chatapp-7b6ad.appspot.com',
    measurementId: 'G-DXX6C72BF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4quBs2tKael0rlbvwTw3SrAnE-W7ErDY',
    appId: '1:748005715080:android:138c797cf78387636a833d',
    messagingSenderId: '748005715080',
    projectId: 'chatapp-7b6ad',
    storageBucket: 'chatapp-7b6ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe8Dm-wMN_7TysbMmVVrvqZpGFv07VOUE',
    appId: '1:748005715080:ios:0718086b27701c2f6a833d',
    messagingSenderId: '748005715080',
    projectId: 'chatapp-7b6ad',
    storageBucket: 'chatapp-7b6ad.appspot.com',
    iosBundleId: 'com.example.managementAppChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe8Dm-wMN_7TysbMmVVrvqZpGFv07VOUE',
    appId: '1:748005715080:ios:19e240d5a11c52f56a833d',
    messagingSenderId: '748005715080',
    projectId: 'chatapp-7b6ad',
    storageBucket: 'chatapp-7b6ad.appspot.com',
    iosBundleId: 'com.example.managementAppChat.RunnerTests',
  );
}
